---
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: ansible
ansible_ssh_pass: ansible
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: ansible
...
