---
- name: Get Facts from ios devices and save them into a csv format
  hosts: all
  gather_facts: no

  vars:
    info_dir: "/home/osboxes/ansible/playbook_facts/facts"
    report_file: "{{ info_dir}}/device-facts.csv"

  tasks:
    - name: Creating/Confirming directory
      file:
        path: "{{ info_dir }}"
        state: directory
      run_once: yes
      delegate_to: localhost

    - name: Get IOS device facts
      ios_facts:
        gather_subset: all

    - name: Save device facts
      template:
        src: template/facts_output.j2
        dest: "{{ report_file }}"
