---
 - name: Configure the login banner
   hosts: all
   gather_facts: no


   tasks:
     - name: Remove old banner
       ios_banner:
          banner: motd
          state: absent

    # - name: Replace with new banner
     #  ios_banner:
      #    banner: motd
       #   text: |
        #    This is the new
        #    multiline login banner
        #  state: present

     - name: Replace banner with banner from file
       ios_banner:
          banner: motd
          text: "{{ lookup('file', './tmp/banner.cfg' )}}"
          state: present
